# Generated by Django 6.0.3 on 2026-06-02 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='current_quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='batch',
            name='initial_quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.batch'),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.order'),
        ),
        migrations.AlterField(
            model_name='salesorderitem',
            name='price_at_sale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.CheckConstraint(condition=models.Q(('current_quantity__gte', 0)), name='batch_current_quantity_not_negative'),
        ),
    ]
