# Generated by Django 6.0.3 on 2026-03-20 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_order_total_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['batch_no']},
        ),
        migrations.AddField(
            model_name='medicine',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='batch',
            name='purchaseOrder',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='inventory.purchaseorder'),
            preserve_default=False,
        ),
    ]
