# Generated by Django 6.0.3 on 2026-03-20 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_batch_options_medicine_low_stock_threshold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='low_stock_threshold',
        ),
    ]
