# Generated by Django 6.0.3 on 2026-03-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_medicine_low_stock_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
